# Generated by Django 4.1.6 on 2023-05-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('near_and_dear', '0003_alter_post_image_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
    ]
